name: Build iOS Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Theos Environment
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Compile Dylib
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
          
      - name: Upload Finished Dylib
        uses: actions/upload-artifact@v3
        with:
          name: MWEngine-Dylib
          path: .theos/obj/*.dylib
